### DISCUSSION TITLE
Can bolt resolve non-Forge modules w/o specifying them directly in the Bolt project?

### DISCUSSION THREAD

**Discussion by gavindidrichsen** [puppet-community/community-triage#7] [Q&A]
This question was posed by Yuri Bushmelev on [Puppet Community Slack](https://puppetcommunity.slack.com/archives/CFD8Z9A4T/p1709650327148529).  The crux is in [this comment below](https://github.com/orgs/voxpupuli/discussions/7#discussioncomment-8695059):

> I would like Bolt to bring dependent non-Forge modules w/o specifying them directly in the Bolt project.

**Comment by jay7x** [comment]
Let me clarify what I'm looking for. Imagine we have a bolt project, that depends on some other private modules hosted in git (not on Forge):

I can include them in a `bolt-project.yaml` file in this way:
```yaml
modules:
  - git: git@gitlab.example.com:platform/my_module1.git
    ref: master
  - git: git@gitlab.example.com:platform/my_module2.git
    ref: master
```

Every repo above is a puppet module with their respective `metadata.json`.

Let's say `my_module1` depends on another module.. Let it be `my_basemodule` hosted in a `git@gitlab.example.com:platform/my_basemodule.git` repo.

How can I bring that dependency to my main project without specifying it explicitly in the `bolt-project.yaml`?

Ideally, I'd like to specify the `my_basemodule` as a dependency in the `my_module1`'s `metadata.json` file. Then I'd expect that `bolt module install --force` will bring it to my project.

Is it possible? That is my original question :)
